server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hutaoying/repo-test     # 配置git仓库的地址
#          search-paths:                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: tyhu317@163.com                                        # git仓库的账号
          password: zhbm176166                                    # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址